### ISSUE TITLE
Questions on Data Preprocessing

### ISSUE THREAD

**Issue by Jaccelerator** [Data-Designer/SEAGULL#1]
As original paper claims that "we retain the users and items greater than 5 interactions", however, at [this line](https://github.com/Data-Designer/SEAGULL/blob/1a161cafb9ad3f912724ca5ed476d98068058ace/src/doubanp.py#L143C6-L143C6), for douban movie dataset, it seems that **only** filter from user side, and the filtering thresold is 20. In this setting (not limited to movie), the data description is not aligned with the statistic dataset information in paper. Besides, the experimental result is extremely higher.  I do not know why it is. Sincerely look forward to your response.

<details>
<summary>Experimental Log</summary>

Thu 26 Oct 2023 19:16:19 INFO  {'model': 'Seagull', 'state': 'info', 'dataset': 'douban_mb', 'num_log': '2', 'checkpoint_dir': 'douban_mb', 'data_A': 'douban_movie', 'data_B': 'douban_book', 'loss_decimal_place': 4, 'learner': 'adam', 'num_m_step': 1, 'warm_up_step': 1, 'learning_rate': 0.0005, 'epochs': 11, 'eval_step': 1, 'eval_batch': 40960, 'stopping_step': 10, 'clip_grad_norm': None, 'valid_metric': ['hit', 'ndcg'], 'valid_metric_bigger': 'hit', 'use_gpu': True, 'device': 'cuda:0', 'weight_decay': 0.0005, 'batch_size': 4096, 'embedding_size': 64, 'n_layers': 2, 'reg_weight': 0.01, 'ssl_temp': 0.1, 'ssl_reg': 1e-07, 'threshold': 2, 'growing_factor': 1.25, 'hyper_layers': 1, 'alpha': 1, 'proto_reg': 8e-08, 'k': 100, 'topk': 10, 'neg_num': 7, 'overlap_ratio': None}
Thu 26 Oct 2023 19:16:19 INFO  loading Doc2Vec object from ../data/douban_movie/Doc2vec_douban_movie_VSize64.model
Thu 26 Oct 2023 19:16:20 INFO  loading vocabulary recursively from ../data/douban_movie/Doc2vec_douban_movie_VSize64.model.vocabulary.* with mmap=None
Thu 26 Oct 2023 19:16:20 INFO  loading trainables recursively from ../data/douban_movie/Doc2vec_douban_movie_VSize64.model.trainables.* with mmap=None
Thu 26 Oct 2023 19:16:20 INFO  loading wv recursively from ../data/douban_movie/Doc2vec_douban_movie_VSize64.model.wv.* with mmap=None
Thu 26 Oct 2023 19:16:20 INFO  loading docvecs recursively from ../data/douban_movie/Doc2vec_douban_movie_VSize64.model.docvecs.* with mmap=None
Thu 26 Oct 2023 19:16:20 INFO  loaded ../data/douban_movie/Doc2vec_douban_movie_VSize64.model
Thu 26 Oct 2023 19:16:21 INFO  loading Doc2Vec object from ../data/douban_book/Doc2vec_douban_book_VSize64.model
Thu 26 Oct 2023 19:16:22 INFO  loading vocabulary recursively from ../data/douban_book/Doc2vec_douban_book_VSize64.model.vocabulary.* with mmap=None
Thu 26 Oct 2023 19:16:22 INFO  loading trainables recursively from ../data/douban_book/Doc2vec_douban_book_VSize64.model.trainables.* with mmap=None
Thu 26 Oct 2023 19:16:22 INFO  loading wv recursively from ../data/douban_book/Doc2vec_douban_book_VSize64.model.wv.* with mmap=None
Thu 26 Oct 2023 19:16:22 INFO  loading docvecs recursively from ../data/douban_book/Doc2vec_douban_book_VSize64.model.docvecs.* with mmap=None
Thu 26 Oct 2023 19:16:22 INFO  loaded ../data/douban_book/Doc2vec_douban_book_VSize64.model
Thu 26 Oct 2023 19:17:01 INFO  {'shape_A': [2718, 34889], 'shape_B': [2718, 95696], 'maxRate_A': 5.0, 'maxRate_B': 5.0}
Thu 26 Oct 2023 19:17:04 INFO  Seagull(
  (user_embeddings_src): Embedding(2718, 64)
  (item_embeddings_src): Embedding(34889, 64)
  (user_embeddings_tgt): Embedding(2718, 64)
  (item_embeddings_tgt): Embedding(95696, 64)
  (bpr_loss): BPRLoss()
  (reg_loss): EmbLoss()
  (sp_loss): SPLoss()
  (layers): ModuleList()
  (net): GraphNet_CrossGCF(
    (layers): ModuleList(
      (0): CrossGCF(
        (W1): Linear(in_features=64, out_features=64, bias=True)
        (W2): Linear(in_features=64, out_features=64, bias=True)
        (W3): Linear(in_features=64, out_features=64, bias=True)
        (attn_fc): Linear(in_features=128, out_features=1, bias=False)
        (leaky_relu): LeakyReLU(negative_slope=0.2)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (1): CrossGCF(
        (W1): Linear(in_features=64, out_features=64, bias=True)
        (W2): Linear(in_features=64, out_features=64, bias=True)
        (W3): Linear(in_features=64, out_features=64, bias=True)
        (attn_fc): Linear(in_features=128, out_features=1, bias=False)
        (leaky_relu): LeakyReLU(negative_slope=0.2)
        (dropout): Dropout(p=0.1, inplace=False)
      )
    )
    (feature_dict): ParameterDict(
        (i): Parameter containing: [torch.cuda.FloatTensor of size 130585x64 (GPU 0)]
        (u): Parameter containing: [torch.cuda.FloatTensor of size 2718x64 (GPU 0)]
    )
  )
)
Thu 26 Oct 2023 19:17:04 WARNING  The parameters [weight_decay] and [reg_weight] are specified simultaneously, which may lead to double regularization.
Thu 26 Oct 2023 19:17:04 INFO  init success!
Thu 26 Oct 2023 19:17:04 INFO  Running E-step ! 
Thu 26 Oct 2023 19:23:35 INFO  epoch 0 training [time: 389.63s, train_loss1: 3841223.5619, train_loss2: 62.5254, train_loss3: 14.0650]
Thu 26 Oct 2023 19:23:35 INFO  epoch 0 training [time: 389.63s, train_loss1: 2720995.2364, train_loss2: 57.8471, train_loss3: 13.9500]
Thu 26 Oct 2023 19:23:35 INFO  epoch 0 evaluating [time: 0.25s, best_scores: src_hit : 0.7602385685884692    src_epoch_hit : 0    tgt_hit : 0.7088744588744589    tgt_epoch_hit : 0    src_ndcg : 0.5186472187694542    src_epoch_ndcg : 0    tgt_ndcg : 0.502913882560622    tgt_epoch_ndcg : 0    ]
Thu 26 Oct 2023 19:23:35 INFO  valid result: 
hit : 0.7602385685884692    ndcg : 0.5186472187694542    
Thu 26 Oct 2023 19:23:35 INFO  valid result: 
hit : 0.7088744588744589    ndcg : 0.502913882560622    
Thu 26 Oct 2023 19:23:36 INFO  Saving current best: ./log/douban_mb/log2/checkpoint/Seagull-Oct-26-2023_19-17-04.pth
Thu 26 Oct 2023 19:23:36 INFO  Running E-step ! 
Thu 26 Oct 2023 19:30:10 INFO  epoch 1 training [time: 394.42s, train_loss1: 3733028.5192, train_loss2: 1.2370, train_loss3: 14.9869, train_loss4: 6.7837]
Thu 26 Oct 2023 19:30:10 INFO  epoch 1 training [time: 394.42s, train_loss1: 2178111.6791, train_loss2: 1.0587, train_loss3: 14.7042, train_loss4: 6.7759]
Thu 26 Oct 2023 19:30:11 INFO  epoch 1 evaluating [time: 0.21s, best_scores: src_hit : 0.7658051689860835    src_epoch_hit : 1    tgt_hit : 0.7738095238095238    tgt_epoch_hit : 1    src_ndcg : 0.5186472187694542    src_epoch_ndcg : 0    tgt_ndcg : 0.563908498863926    tgt_epoch_ndcg : 1    ]
Thu 26 Oct 2023 19:30:11 INFO  valid result: 
hit : 0.7658051689860835    ndcg : 0.5161435692718778    
Thu 26 Oct 2023 19:30:11 INFO  valid result: 
hit : 0.7738095238095238    ndcg : 0.563908498863926    
Thu 26 Oct 2023 19:30:11 INFO  Saving current best: ./log/douban_mb/log2/checkpoint/Seagull-Oct-26-2023_19-17-04.pth
Thu 26 Oct 2023 19:30:11 INFO  Running E-step ! 
Thu 26 Oct 2023 19:36:46 INFO  epoch 2 training [time: 394.13s, train_loss1: 3634133.5212, train_loss2: 1.4076, train_loss3: 16.8610, train_loss4: 6.7837]
Thu 26 Oct 2023 19:36:46 INFO  epoch 2 training [time: 394.13s, train_loss1: 1762421.5710, train_loss2: 1.0350, train_loss3: 17.1331, train_loss4: 6.7759]
Thu 26 Oct 2023 19:36:46 INFO  epoch 2 evaluating [time: 0.23s, best_scores: src_hit : 0.7658051689860835    src_epoch_hit : 1    tgt_hit : 0.8506493506493507    tgt_epoch_hit : 2    src_ndcg : 0.5186472187694542    src_epoch_ndcg : 0    tgt_ndcg : 0.6125569451025458    tgt_epoch_ndcg : 2    ]
Thu 26 Oct 2023 19:36:46 INFO  valid result: 
hit : 0.7646123260437375    ndcg : 0.5162358863386921    
Thu 26 Oct 2023 19:36:46 INFO  valid result: 
hit : 0.8506493506493507    ndcg : 0.6125569451025458    
Thu 26 Oct 2023 19:36:47 INFO  Saving current best: ./log/douban_mb/log2/checkpoint/Seagull-Oct-26-2023_19-17-04.pth
Thu 26 Oct 2023 19:36:47 INFO  Running E-step ! 
Thu 26 Oct 2023 19:43:22 INFO  epoch 3 training [time: 395.31s, train_loss1: 3628452.1642, train_loss2: 1.4073, train_loss3: 18.1799, train_loss4: 6.7837]
Thu 26 Oct 2023 19:43:22 INFO  epoch 3 training [time: 395.31s, train_loss1: 1516038.9057, train_loss2: 1.0521, train_loss3: 19.0642, train_loss4: 6.7759]
Thu 26 Oct 2023 19:43:23 INFO  epoch 3 evaluating [time: 0.21s, best_scores: src_hit : 0.7685884691848907    src_epoch_hit : 3    tgt_hit : 0.8782467532467533    tgt_epoch_hit : 3    src_ndcg : 0.5186472187694542    src_epoch_ndcg : 0    tgt_ndcg : 0.6282285451187671    tgt_epoch_ndcg : 3    ]
Thu 26 Oct 2023 19:43:23 INFO  valid result: 
hit : 0.7685884691848907    ndcg : 0.5159411711644925    
Thu 26 Oct 2023 19:43:23 INFO  valid result: 
hit : 0.8782467532467533    ndcg : 0.6282285451187671    
Thu 26 Oct 2023 19:43:23 INFO  Saving current best: ./log/douban_mb/log2/checkpoint/Seagull-Oct-26-2023_19-17-04.pth
Thu 26 Oct 2023 19:43:23 INFO  Running E-step ! 
Thu 26 Oct 2023 19:49:58 INFO  epoch 4 training [time: 394.26s, train_loss1: 3595320.1869, train_loss2: 1.4194, train_loss3: 18.5136, train_loss4: 6.7837]
Thu 26 Oct 2023 19:49:58 INFO  epoch 4 training [time: 394.26s, train_loss1: 1371546.2660, train_loss2: 1.0712, train_loss3: 19.6332, train_loss4: 6.7759]
Thu 26 Oct 2023 19:49:58 INFO  epoch 4 evaluating [time: 0.22s, best_scores: src_hit : 0.7685884691848907    src_epoch_hit : 3    tgt_hit : 0.8782467532467533    tgt_epoch_hit : 3    src_ndcg : 0.5186472187694542    src_epoch_ndcg : 0    tgt_ndcg : 0.6282285451187671    tgt_epoch_ndcg : 3    ]
Thu 26 Oct 2023 19:49:58 INFO  valid result: 
hit : 0.6119284294234593    ndcg : 0.384595952578369    
Thu 26 Oct 2023 19:49:58 INFO  valid result: 
hit : 0.797077922077922    ndcg : 0.5452639816483752    
Thu 26 Oct 2023 19:49:58 INFO  Running E-step ! 
Thu 26 Oct 2023 19:56:34 INFO  epoch 5 training [time: 396.11s, train_loss1: 3571678.6592, train_loss2: 1.4191, train_loss3: 18.8264, train_loss4: 6.7837]
Thu 26 Oct 2023 19:56:34 INFO  epoch 5 training [time: 396.11s, train_loss1: 1277477.3235, train_loss2: 1.0734, train_loss3: 19.9363, train_loss4: 6.7759]
Thu 26 Oct 2023 19:56:35 INFO  epoch 5 evaluating [time: 0.25s, best_scores: src_hit : 0.7777335984095427    src_epoch_hit : 5    tgt_hit : 0.8917748917748918    tgt_epoch_hit : 5    src_ndcg : 0.5283886364441571    src_epoch_ndcg : 5    tgt_ndcg : 0.6495480285623081    tgt_epoch_ndcg : 5    ]
Thu 26 Oct 2023 19:56:35 INFO  valid result: 
hit : 0.7777335984095427    ndcg : 0.5283886364441571    
Thu 26 Oct 2023 19:56:35 INFO  valid result: 
hit : 0.8917748917748918    ndcg : 0.6495480285623081    
Thu 26 Oct 2023 19:56:35 INFO  Saving current best: ./log/douban_mb/log2/checkpoint/Seagull-Oct-26-2023_19-17-04.pth
Thu 26 Oct 2023 19:56:35 INFO  Running E-step ! 
Thu 26 Oct 2023 20:03:10 INFO  epoch 6 training [time: 394.35s, train_loss1: 3596098.0674, train_loss2: 1.4191, train_loss3: 18.8078, train_loss4: 6.7837]
Thu 26 Oct 2023 20:03:10 INFO  epoch 6 training [time: 394.35s, train_loss1: 1265425.6670, train_loss2: 1.0693, train_loss3: 19.9811, train_loss4: 6.7759]
Thu 26 Oct 2023 20:03:10 INFO  epoch 6 evaluating [time: 0.21s, best_scores: src_hit : 0.7777335984095427    src_epoch_hit : 5    tgt_hit : 0.8917748917748918    tgt_epoch_hit : 5    src_ndcg : 0.5283886364441571    src_epoch_ndcg : 5    tgt_ndcg : 0.6495480285623081    tgt_epoch_ndcg : 5    ]
Thu 26 Oct 2023 20:03:10 INFO  valid result: 
hit : 0.7709741550695826    ndcg : 0.5267605625762477    
Thu 26 Oct 2023 20:03:10 INFO  valid result: 
hit : 0.8906926406926406    ndcg : 0.6492860265084115    
Thu 26 Oct 2023 20:03:10 INFO  Running E-step ! 
Thu 26 Oct 2023 20:09:44 INFO  epoch 7 training [time: 393.36s, train_loss1: 3737466.9419, train_loss2: 1.4198, train_loss3: 18.5437, train_loss4: 6.7837]
Thu 26 Oct 2023 20:09:44 INFO  epoch 7 training [time: 393.36s, train_loss1: 1318199.8414, train_loss2: 1.0712, train_loss3: 19.7221, train_loss4: 6.7759]
Thu 26 Oct 2023 20:09:44 INFO  epoch 7 evaluating [time: 0.21s, best_scores: src_hit : 0.7777335984095427    src_epoch_hit : 5    tgt_hit : 0.8917748917748918    tgt_epoch_hit : 5    src_ndcg : 0.5315119716640253    src_epoch_ndcg : 7    tgt_ndcg : 0.6495480285623081    tgt_epoch_ndcg : 5    ]
Thu 26 Oct 2023 20:09:44 INFO  valid result: 
hit : 0.7761431411530815    ndcg : 0.5315119716640253    
Thu 26 Oct 2023 20:09:44 INFO  valid result: 
hit : 0.8793290043290043    ndcg : 0.6346097755624912    
Thu 26 Oct 2023 20:09:45 INFO  Saving current best: ./log/douban_mb/log2/checkpoint/Seagull-Oct-26-2023_19-17-04.pth
Thu 26 Oct 2023 20:09:45 INFO  Running E-step ! 
Thu 26 Oct 2023 20:16:17 INFO  epoch 8 training [time: 392.20s, train_loss1: 3622324.8711, train_loss2: 1.4185, train_loss3: 18.4859, train_loss4: 6.7837]
Thu 26 Oct 2023 20:16:17 INFO  epoch 8 training [time: 392.20s, train_loss1: 1253687.6518, train_loss2: 1.0707, train_loss3: 19.3408, train_loss4: 6.7759]
Thu 26 Oct 2023 20:16:18 INFO  epoch 8 evaluating [time: 0.21s, best_scores: src_hit : 0.7777335984095427    src_epoch_hit : 5    tgt_hit : 0.8917748917748918    tgt_epoch_hit : 5    src_ndcg : 0.5315119716640253    src_epoch_ndcg : 7    tgt_ndcg : 0.6495480285623081    tgt_epoch_ndcg : 5    ]
Thu 26 Oct 2023 20:16:18 INFO  valid result: 
hit : 0.7713717693836978    ndcg : 0.5216290215529865    
Thu 26 Oct 2023 20:16:18 INFO  valid result: 
hit : 0.8722943722943723    ndcg : 0.6307437618052651    
Thu 26 Oct 2023 20:16:18 INFO  Running E-step ! 
Thu 26 Oct 2023 20:22:51 INFO  epoch 9 training [time: 393.48s, train_loss1: 3655372.3230, train_loss2: 1.4189, train_loss3: 18.1966, train_loss4: 6.7837]
Thu 26 Oct 2023 20:22:51 INFO  epoch 9 training [time: 393.48s, train_loss1: 1220392.6205, train_loss2: 1.0718, train_loss3: 19.1274, train_loss4: 6.7759]
Thu 26 Oct 2023 20:22:52 INFO  epoch 9 evaluating [time: 0.21s, best_scores: src_hit : 0.7777335984095427    src_epoch_hit : 5    tgt_hit : 0.8917748917748918    tgt_epoch_hit : 5    src_ndcg : 0.5315119716640253    src_epoch_ndcg : 7    tgt_ndcg : 0.6495480285623081    tgt_epoch_ndcg : 5    ]
Thu 26 Oct 2023 20:22:52 INFO  valid result: 
hit : 0.7558648111332008    ndcg : 0.5054528944534495    
Thu 26 Oct 2023 20:22:52 INFO  valid result: 
hit : 0.8820346320346321    ndcg : 0.632607392144248    
Thu 26 Oct 2023 20:22:52 INFO  Running E-step ! 
Thu 26 Oct 2023 20:29:27 INFO  epoch 10 training [time: 395.22s, train_loss1: 3559461.7603, train_loss2: 1.4185, train_loss3: 18.6286, train_loss4: 6.7837]
Thu 26 Oct 2023 20:29:27 INFO  epoch 10 training [time: 395.22s, train_loss1: 1145788.3025, train_loss2: 1.0710, train_loss3: 19.3414, train_loss4: 6.7759]
Thu 26 Oct 2023 20:29:27 INFO  epoch 10 evaluating [time: 0.24s, best_scores: src_hit : 0.7777335984095427    src_epoch_hit : 5    tgt_hit : 0.8917748917748918    tgt_epoch_hit : 5    src_ndcg : 0.5315119716640253    src_epoch_ndcg : 7    tgt_ndcg : 0.6495480285623081    tgt_epoch_ndcg : 5    ]
Thu 26 Oct 2023 20:29:27 INFO  valid result: 
hit : 0.7717693836978131    ndcg : 0.5280177752712293    
Thu 26 Oct 2023 20:29:27 INFO  valid result: 
hit : 0.8603896103896104    ndcg : 0.6197801990421871    
Thu 26 Oct 2023 20:29:27 INFO  Finished training~
Thu 26 Oct 2023 20:29:27 INFO  Loading model structure and parameters from ./log/douban_mb/log2/checkpoint/Seagull-Oct-26-2023_19-17-04.pth
Thu 26 Oct 2023 20:29:28 INFO  best valid : {'src_hit': 0.7777335984095427, 'src_epoch_hit': 5, 'tgt_hit': 0.8917748917748918, 'tgt_epoch_hit': 5, 'src_ndcg': 0.5315119716640253, 'src_epoch_ndcg': 7, 'tgt_ndcg': 0.6495480285623081, 'tgt_epoch_ndcg': 5}
Thu 26 Oct 2023 20:29:28 INFO  test result: (defaultdict(<class 'list'>, {'hit': 0.7761431411530815, 'ndcg': 0.5315119716640253}), defaultdict(<class 'list'>, {'hit': 0.8793290043290043, 'ndcg': 0.6346097755624912}))
</details>

**Comment by Data-Designer** [comment]
When it comes to datasets, we adhere to the data processing approach used in gadtcdr. We are sorry to uploaded the false version. You could refer to gadtcdr to do the same data process. (Please note that you could firstly filter the item and then filter the user according the issue proposed in gadtcdr)
Regarding performance, have you trained Doc2vec_douban_movie_VSize64 multiple times? It seems like in douban dataset, it maybe overfitting if you train it for many times.

**Comment by Jaccelerator** [comment]
Thanks for your kindly and timely reply, I will refer to GADTCDR for more advice.
But I am still confused how Doc2vec_douban_movie_VSize64 models are trained multiple times: once I run the preprocess script and then these doc2vec models will be regenerated?

**Comment by Jaccelerator** [comment]
Sorry to disturb you, again. I find that for Amazon' dataset, the statistic infomation in SEAGULL's paper is not consistent with the CATN's. I do not understand how to filter these datasets to obtain the results as paper reported.  
So would you kindly provide the **processed dataset and corresponding Doc2Vec Models/Hyperparameters** if convenient? @Data-Designer My email is jyaccelerator@gmail.com (thx

**Comment by Data-Designer** [comment]
I found a version on my current computer (the company's computer was recycled), I hope it will be useful to you. 
For Amazon, I remember filtering according to 30. 




| |
赵闯
|
|
***@***.***
|
---- Replied Message ----
| From | Yu ***@***.***> |
| Date | 11/2/2023 20:11 |
| To | ***@***.***> |
| Cc | Zhao ***@***.***> ,
State ***@***.***> |
| Subject | Re: [Data-Designer/SEAGULL] Questions on Data Preprocessing (Issue #1) |

Sorry to disturb you, again. I find that for Amazon' dataset, the statistic infomation in SEAGULL's paper is not consistent with the CATN's. I do not understand how to filter these datasets to obtain the results as paper reported.
So would you kindly provide the processed dataset and corresponding Doc2Vec Models/Hyperparameters if convenient?
